#!/usr/bin/env bash
# Offline local telemetry contract. Bash 3.2 compatible.
set -u
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"; TEL="$SCRIPT_DIR/../telemetry.sh"; TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
FAILURES=0; ok(){ echo "ok   - $1"; }; bad(){ echo "NOT OK - $1";FAILURES=$((FAILURES+1));}
REPO="$TMP/repo"; mkdir -p "$REPO/.review" "$REPO/.agent-workflow"; git -C "$REPO" init -q;git -C "$REPO" config user.name smoke;git -C "$REPO" config user.email smoke@example.test;printf x > "$REPO/a";git -C "$REPO" add a;git -C "$REPO" commit -qm base;HEAD="$(git -C "$REPO" rev-parse HEAD)";printf '%s' 'target-local-salt-not-a-secret' > "$REPO/.agent-workflow/telemetry-salt"
make_round(){ issue="$1"; node - "$ROOT/schemas/fixtures/round_state.valid.json" "$REPO" "$HEAD" "$issue" <<'NODE'
const fs=require("fs"),path=require("path"),[src,root,head,issue]=process.argv.slice(2),o=JSON.parse(fs.readFileSync(src));o.issue={number:Number(issue),title:"telemetry"};o.tier={name:"standard",rationale:"smoke"};o.revision=1;o.base_branch="master";o.base_sha=head;o.head_sha=head;o.worktree_path=root;o.contract={objective:"observe",touch_allowlist:["a"],prohibitions:["no network"],verify_filter:"smoke",test_discovery_command:"printf AC"};o.acceptance={expected_test_count:1,criteria:[{id:"AC",statement:"green"}]};o.decisions=[];o.prior_findings=[];delete o.round_control;o.commit_scope={commits:[]};o.live_probes=[];o.artifact_pointers=[{artifact_type:"pr_draft",path:`.review/ISSUE-${issue}-PR-DRAFT.json`},{artifact_type:"review",path:`.review/ISSUE-${issue}-REVIEW.json`}];fs.writeFileSync(path.join(root,`.review/ISSUE-${issue}-ROUND-STATE.json`),JSON.stringify(o));
NODE
}
make_run(){ issue="$1";attempt="$2";status="$3";start="$4";end="$5";ec="$6"; node - "$REPO/.review/ISSUE-$issue-RUN.json" "$issue" "$attempt" "$status" "$start" "$end" "$ec" <<'NODE'
const fs=require("fs"),[f,issue,attempt,status,start,end,ec]=process.argv.slice(2),o={schema_version:"1",artifact_type:"codex_run",issue:Number(issue),attempt:Number(attempt),started_at:start,updated_at:end,status};if(status==="exited")o.exit_code=Number(ec);fs.writeFileSync(f,JSON.stringify(o));
NODE
}
make_verify(){ issue="$1";kind="$2"; node - "$REPO/.review/ISSUE-$issue-VERIFY.json" "$REPO" "$HEAD" "$issue" "$kind" <<'NODE'
const fs=require("fs"),[f,root,head,issue,kind]=process.argv.slice(2),pass=kind==="pass",o={schema_version:"1",artifact_type:"verify_result",producer_role:"VERIFIER",issue:Number(issue),branch:"master",head_sha:head,cwd:root,verify_cmd:"verify smoke",db_target:{host:"localhost",database:"smoke",role:"verifier"},clean_state:{sentinel:{expected:"clean",actual:"clean"},migration_hash:{expected:"same",actual:"same"},role:{name:"verifier",superuser:false}},verdict:{passed:pass?1:0,failed:pass?0:1,pending:0,exit_code:pass?0:1},classifier:pass?"PASS":"FAIL",failures:pass?[]:[{code:"failed",expected:"0",actual:"1"}],created_at:"2026-07-20T00:01:00Z"};fs.writeFileSync(f,JSON.stringify(o));
NODE
}
make_review(){ issue="$1"; node - "$REPO/.review/ISSUE-$issue-REVIEW.json" "$HEAD" "$issue" <<'NODE'
const fs=require("fs"),[f,head,issue]=process.argv.slice(2);fs.writeFileSync(f,JSON.stringify({schema_version:"1",artifact_type:"review",lifecycle:"final",producer_role:"REVIEWER",issue:{number:Number(issue)},reviewed_head_sha:head,status:"fail",checklist:[{item:"fix",met:false}],findings:[{severity:"fix",description:"repair"}],patch_instructions:"repair"}));
NODE
}
make_closure(){ issue="$1";round="$2";status="$3";head="${4-$HEAD}"; node - "$ROOT" "$REPO" "$issue" "$round" "$status" "$head" <<'NODE'
const fs=require("fs"),path=require("path"),crypto=require("crypto"),[root,repo,issueRaw,roundRaw,status,head]=process.argv.slice(2),issue=Number(issueRaw),round=Number(roundRaw),review=path.join(repo,".review"),load=n=>JSON.parse(fs.readFileSync(path.join(root,"schemas/fixtures",n))),write=(n,o)=>{const f=path.join(review,n);fs.writeFileSync(f,JSON.stringify(o));return f},digest=f=>crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex"),run=JSON.parse(fs.readFileSync(path.join(review,`ISSUE-${issue}-RUN.json`))),end=Date.parse(run.updated_at),iso=n=>new Date(n).toISOString();
const integration=load("integration_result.valid.json");Object.assign(integration,{issue,round,manifest_revision:1,plan_revision:1,base_head:head,candidate_head:head,created_at:iso(end-2000)});integration.steps=integration.steps.map(step=>({...step,source_head:head,resulting_head:head}));const integrationFile=write(`ISSUE-${issue}-INTEGRATION.json`,integration);
const evidence=load("candidate_evidence_set.valid.json");Object.assign(evidence,{issue,round,manifest_revision:1,plan_revision:1,candidate_head:head,attempt_id:`attempt-${round}`,created_at:iso(end-1000)});evidence.evidence=evidence.evidence.map(entry=>({...entry,path:`.review/ISSUE-${issue}-REVIEW.json`,attempt_id:`attempt-${round}`}));const evidenceFile=write(`ISSUE-${issue}-CANDIDATE-EVIDENCE.json`,evidence);
const closure=load("candidate_closure.valid.json");Object.assign(closure,{issue,round,manifest_revision:1,plan_revision:1,candidate_head:head,attempt_id:`attempt-${round}`,integration_sha256:digest(integrationFile),evidence_set_sha256:digest(evidenceFile),status,reason_codes:status==="closed"?[]:["not_closed"],evaluated_at:iso(end+1000)});write(`ISSUE-${issue}-CLOSURE.json`,closure);
NODE
}
collect(){ issue="$1";attempt="$2";role="$3";usage="$4";retry="$5";evidence_kind="$6";with_closure="${7-no}";model="${8-gpt-5.6-terra}";salt_file="${9-.agent-workflow/telemetry-salt}";store="${10-}"; set -- --issue "$issue" --worktree "$REPO" --round-state ".review/ISSUE-$issue-ROUND-STATE.json" --run ".review/ISSUE-$issue-RUN.json" --manifest-revision 1 --attempt "$attempt" --round 1 --role "$role" --task-class workflow --model "$model" --effort low --transport cmux --salt-file "$salt_file" --usage "$usage"; [ -n "$retry" ] && set -- "$@" --retry-of "$retry"; [ "$evidence_kind" = verify ] && set -- "$@" --verify ".review/ISSUE-$issue-VERIFY.json"; [ "$evidence_kind" = review ] && set -- "$@" --review ".review/ISSUE-$issue-REVIEW.json"; [ "$with_closure" = yes ] && set -- "$@" --closure ".review/ISSUE-$issue-CLOSURE.json" --integration ".review/ISSUE-$issue-INTEGRATION.json" --evidence-set ".review/ISSUE-$issue-CANDIDATE-EVIDENCE.json"; [ -n "$store" ] && set -- "$@" --store "$store"; bash "$TEL" collect "$@"; }
OBS='{"kind":"observed","input_tokens":100,"output_tokens":20,"cost":1.25,"currency":"USD","source":"provider_usage","provenance_version":"pricing-2026-07"}'
EST='{"kind":"estimated","input_tokens":80,"output_tokens":10,"cost":0.5,"currency":"USD","source":"local_token_estimator","provenance_version":"v1"}'
NA='{"kind":"unavailable","input_tokens":null,"output_tokens":null,"cost":null,"currency":null,"source":null,"provenance_version":null}'

if node - "$ROOT/scripts/lib/json-schema-subset.cjs" "$ROOT/schemas/telemetry_sample.schema.json" "$ROOT/schemas/fixtures/telemetry_sample.valid.json" "$ROOT/schemas/fixtures/telemetry_sample.invalid.json" "$ROOT/schemas/telemetry_report.schema.json" "$ROOT/schemas/fixtures/telemetry_report.valid.json" "$ROOT/schemas/fixtures/telemetry_report.invalid.json" "$ROOT/schemas/candidate_closure.schema.json" "$ROOT/schemas/fixtures/candidate_closure.valid.json" "$ROOT/schemas/fixtures/candidate_closure.invalid.json" "$ROOT/schemas/integration_result.schema.json" "$ROOT/schemas/fixtures/integration_result.valid.json" "$ROOT/schemas/fixtures/integration_result.invalid.json" "$ROOT/schemas/candidate_evidence_set.schema.json" "$ROOT/schemas/fixtures/candidate_evidence_set.valid.json" "$ROOT/schemas/fixtures/candidate_evidence_set.invalid.json" <<'NODE'
const fs=require("fs"),[validator,...files]=process.argv.slice(2),{validate}=require(validator);
for(let i=0;i<files.length;i+=3){const schema=JSON.parse(fs.readFileSync(files[i])),valid=JSON.parse(fs.readFileSync(files[i+1])),invalid=JSON.parse(fs.readFileSync(files[i+2]));if(validate(schema,valid).length||!validate(schema,invalid).length)process.exit(1);}
NODE
then ok "AC-TEL-1/6 schemas accept valid and reject invalid fixtures";else bad "AC-TEL-1/6 schema fixtures";fi
if node - "$ROOT/scripts/lib/json-schema-subset.cjs" "$ROOT/scripts/lib/telemetry-sample.cjs" "$ROOT/schemas/telemetry_sample.schema.json" "$ROOT/schemas/candidate_closure.schema.json" "$ROOT/schemas/fixtures/telemetry_sample.closure.valid.json" "$ROOT/schemas/fixtures/telemetry_sample.closure.invalid.json" <<'NODE'
const fs=require("fs"),[validatorFile,semanticFile,sampleSchemaFile,closureSchemaFile,validFile,invalidFile]=process.argv.slice(2),{validate}=require(validatorFile),{validateTelemetrySampleClosure}=require(semanticFile),sampleSchema=JSON.parse(fs.readFileSync(sampleSchemaFile)),closureSchema=JSON.parse(fs.readFileSync(closureSchemaFile)),valid=JSON.parse(fs.readFileSync(validFile)),invalid=JSON.parse(fs.readFileSync(invalidFile));
if(validate(sampleSchema,valid).length||validate(sampleSchema,invalid).length)process.exit(1);
if(validateTelemetrySampleClosure(valid,closureSchema,validate).length)process.exit(2);
const errors=validateTelemetrySampleClosure(invalid,closureSchema,validate);process.exit(errors.includes("candidate_evidence_digest_mismatch")?0:3);
NODE
then ok "AC-TEL-3 closure fixtures bind integration and candidate evidence semantically";else bad "AC-TEL-3 closure fixture semantics";fi
if [ "$(shasum -a 256 "$ROOT/schemas/candidate_closure.schema.json"|awk '{print $1}')" = 183abe14056b62f2c70a2b85858c59b3a4cf4d9b72bde375bdbe17966d72c54c ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/candidate_closure.valid.json"|awk '{print $1}')" = a3e67183048f9238a6b114b755253418af56c13ff99eeeac517576353388e78a ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/candidate_closure.invalid.json"|awk '{print $1}')" = a28007a841e2f0183002c672359939ee8839e91419cfa0f62f92ae4240560d31 ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/candidate_closure.timestamp.invalid.json"|awk '{print $1}')" = 6554bead13587159417a9f9c867153545e017f6e557b4e0ff588fbd3f71bca13 ];then ok "AC-TEL-3 canonical #14 closure contract provenance";else bad "AC-TEL-3 closure contract provenance";fi
node - "$ROOT/scripts/lib/json-schema-subset.cjs" "$ROOT/schemas/candidate_closure.schema.json" "$ROOT/schemas/fixtures/candidate_closure.timestamp.invalid.json" <<'NODE'
const fs=require("fs"),[validator,schemaFile,fixture]=process.argv.slice(2),{validate}=require(validator),schema=JSON.parse(fs.readFileSync(schemaFile)),value=JSON.parse(fs.readFileSync(fixture));process.exit(validate(schema,value).length>0?0:1);
NODE
[ "$?" -eq 0 ]&&ok "AC-TEL-3 canonical closure rejects non-RFC3339 timestamp"||bad "AC-TEL-3 closure timestamp"
if [ "$(shasum -a 256 "$ROOT/schemas/integration_result.schema.json"|awk '{print $1}')" = a891b78a786293c8cf61525eb354f00466bfe8a743ec49d1ef63cbdb33987d4b ]&&[ "$(shasum -a 256 "$ROOT/schemas/candidate_evidence_set.schema.json"|awk '{print $1}')" = f2d81d4f72f47aa717310dfe22869b172cd337c24bd23ea55b46d3139c003b15 ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/integration_result.valid.json"|awk '{print $1}')" = 5fd78c52872c3f733e14908e076c4fcad9be304f9f9a0d6d573f494604ae8254 ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/integration_result.invalid.json"|awk '{print $1}')" = 65df957d7562d804f7375de59fd311db6705c227f59d2bdcc716afe7ef8e4e1d ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/candidate_evidence_set.valid.json"|awk '{print $1}')" = 654d5f8ad9c0680aa99d467b042288a687755b632416d7383c8db5d387e987f6 ]&&[ "$(shasum -a 256 "$ROOT/schemas/fixtures/candidate_evidence_set.invalid.json"|awk '{print $1}')" = 2f23aa45dcc3b7bcb808eefcda2bc10b0696e64a8f78bbcf5ac5fcfec1679c4d ];then ok "AC-TEL-3 canonical #14 dependency contract provenance";else bad "AC-TEL-3 dependency contract provenance";fi

# AC-TEL-1/2/3: fail -> review retry -> verified green, truthful usage kinds.
make_round 18;make_run 18 1 exited 2026-07-20T00:00:00Z 2026-07-20T00:01:00Z 1;make_verify 18 fail;S1="$(collect 18 1 implementation "$OBS" "" verify | cut -f1)"; collect 18 1 implementation "$OBS" "" verify >/dev/null; [ "$?" -eq 0 ]&&ok "AC-TEL-1 duplicate collection is idempotent"||bad "AC-TEL-1 duplicate"
collect 18 1 implementation "$EST" "" verify >/dev/null 2>&1; [ "$?" -ne 0 ]&&ok "AC-TEL-1 conflicting rewrite fails"||bad "AC-TEL-1 conflict"
make_run 18 2 exited 2026-07-20T00:02:00Z 2026-07-20T00:03:00Z 0;make_review 18;S2="$(collect 18 2 review "$EST" "$S1" review|cut -f1)";make_run 18 3 exited 2026-07-20T00:04:00Z 2026-07-20T00:05:00Z 0;make_verify 18 pass;make_closure 18 1 closed;S3="$(collect 18 3 verification "$NA" "$S2" verify yes|cut -f1)"
if node -e 'const fs=require("fs"),p=process.argv[1],files=fs.readdirSync(p).map(f=>JSON.parse(fs.readFileSync(p+"/"+f)));process.exit(files.some(s=>s.usage.kind==="observed")&&files.some(s=>s.usage.kind==="estimated")&&files.some(s=>s.usage.kind==="unavailable"&&s.usage.cost===null)&&files.some(s=>s.terminal==="green")?0:1)' "$REPO/.agent-workflow/telemetry/samples";then ok "AC-TEL-2 observed estimated unavailable remain distinct";else bad "AC-TEL-2 usage honesty";fi

# Genuine #14 producer fixture supports first-try canonical green; VERIFY-only remains non-green.
make_round 19;make_run 19 1 exited 2026-07-20T01:00:00Z 2026-07-20T01:01:00Z 0;make_verify 19 pass;make_closure 19 1 closed;collect 19 1 verification "$OBS" "" verify yes >/dev/null
make_round 27;make_run 27 1 exited 2026-07-20T01:02:00Z 2026-07-20T01:03:00Z 0;make_verify 27 pass;collect 27 1 verification "$OBS" "" verify >/dev/null
make_round 20;make_run 20 1 exhausted 2026-07-20T02:00:00Z 2026-07-20T02:01:00Z 1;collect 20 1 implementation "$NA" "" none >/dev/null
make_round 21;make_run 21 1 exited 2026-07-20T03:00:00Z 2026-07-20T03:01:00Z 1;collect 21 1 implementation "$NA" aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa none >/dev/null
# Cross-issue retry edges and non-contiguous admitted attempts cannot form a complete chain.
make_round 23;make_run 23 2 exited 2026-07-20T03:02:00Z 2026-07-20T03:03:00Z 0;make_verify 23 pass;make_closure 23 1 closed;collect 23 2 verification "$OBS" "$S1" verify yes >/dev/null
make_round 24;make_run 24 1 exited 2026-07-20T03:04:00Z 2026-07-20T03:05:00Z 1;J1="$(collect 24 1 implementation "$NA" "" none|cut -f1)";make_run 24 9 exited 2026-07-20T03:06:00Z 2026-07-20T03:07:00Z 0;make_verify 24 pass;make_closure 24 1 closed;collect 24 9 verification "$OBS" "$J1" verify yes >/dev/null
# Mixed-model routing remains visible per attempt but is not attributed to one model.
make_round 25;make_run 25 1 exited 2026-07-20T03:08:00Z 2026-07-20T03:09:00Z 1;M1="$(collect 25 1 implementation "$OBS" "" none no gpt-5.6-terra|cut -f1)";make_run 25 2 exited 2026-07-20T03:10:00Z 2026-07-20T03:11:00Z 0;make_verify 25 pass;make_closure 25 1 closed;collect 25 2 verification "$EST" "$M1" verify yes gpt-5.6-sol >/dev/null
ALLOC_HASH="$(shasum -a 256 "$ROOT/model-alloc.json"|awk '{print $1}')";bash "$TEL" report --worktree "$REPO" --from 2026-07-01T00:00:00Z --to 2026-08-01T00:00:00Z --minimum-samples 1 --minimum-completeness 0 > "$TMP/report.json";REPORT_EC=$?;ALLOC_AFTER="$(shasum -a 256 "$ROOT/model-alloc.json"|awk '{print $1}')"
if [ "$REPORT_EC" -eq 0 ]&&node -e 'const r=require(process.argv[1]),c=r.chains.find(x=>x.issue===18),n=r.chains.find(x=>x.issue===20),i=r.chains.find(x=>x.issue===21),x=r.chains.find(x=>x.issue===23),j=r.chains.find(x=>x.issue===24),m=r.chains.find(x=>x.issue===25),g=r.chains.find(x=>x.issue===19),v=r.chains.find(x=>x.issue===27);process.exit(c&&c.complete&&c.green&&c.project_pseudonym.length===64&&c.round===1&&c.manifest_revision===1&&c.attempts===3&&c.roles.length===3&&c.observed_cost===1.25&&c.estimated_cost===.5&&c.unavailable_samples===1&&n&&!n.green&&i&&!i.complete&&x&&!x.complete&&j&&!j.complete&&m&&m.complete&&m.allocation_mode==="mixed_model"&&m.allocations.map(a=>a.model).join(",")==="gpt-5.6-terra,gpt-5.6-sol"&&r.suppressed_cohorts.includes("mixed-model:"+m.chain_id)&&g&&g.complete&&g.green&&v&&!v.green?0:1)' "$TMP/report.json";then ok "AC-TEL-5 canonical closure, immutable retry lineage, and mixed-model allocation";else bad "AC-TEL-5 chain report";fi
# The report independently rejects a stored green claim whose closure digest no longer matches its source artifact record.
node - "$REPO/.agent-workflow/telemetry/samples/$S3.json" <<'NODE'
const fs=require("fs"),f=process.argv[2],o=JSON.parse(fs.readFileSync(f));o.closure.sha256="f".repeat(64);fs.writeFileSync(f,JSON.stringify(o));
NODE
bash "$TEL" report --worktree "$REPO" --from 2026-07-01T00:00:00Z --to 2026-08-01T00:00:00Z --minimum-samples 1 --minimum-completeness 0 >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 report rejects forged closure digest"||bad "AC-TEL-3 report closure semantics"
node - "$REPO/.agent-workflow/telemetry/samples/$S3.json" <<'NODE'
const fs=require("fs"),f=process.argv[2],o=JSON.parse(fs.readFileSync(f));o.closure.sha256=o.artifacts.find(a=>a.kind==="candidate_closure").sha256;fs.writeFileSync(f,JSON.stringify(o));
NODE
node - "$REPO/.agent-workflow/telemetry/samples/$S3.json" <<'NODE'
const fs=require("fs"),f=process.argv[2],o=JSON.parse(fs.readFileSync(f));o.closure.value.evaluated_at="not-a-time";fs.writeFileSync(f,JSON.stringify(o));
NODE
bash "$TEL" report --worktree "$REPO" --from 2026-07-01T00:00:00Z --to 2026-08-01T00:00:00Z --minimum-samples 1 --minimum-completeness 0 >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 report reuses canonical RFC3339 closure schema"||bad "AC-TEL-3 report closure schema"
node - "$REPO/.agent-workflow/telemetry/samples/$S3.json" <<'NODE'
const fs=require("fs"),f=process.argv[2],o=JSON.parse(fs.readFileSync(f));o.closure.value.evaluated_at="2026-07-20T00:02:00Z";fs.writeFileSync(f,JSON.stringify(o));
NODE
node - "$REPO/.agent-workflow/telemetry/samples/$S2.json" <<'NODE'
const fs=require("fs"),f=process.argv[2],o=JSON.parse(fs.readFileSync(f));o.retry_of="";fs.writeFileSync(f,JSON.stringify(o));
NODE
bash "$TEL" report --worktree "$REPO" --from 2026-07-01T00:00:00Z --to 2026-08-01T00:00:00Z --minimum-samples 1 --minimum-completeness 0 >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-5 report rejects mutated retry identity"||bad "AC-TEL-5 retry identity"
node - "$REPO/.agent-workflow/telemetry/samples/$S2.json" "$S1" <<'NODE'
const fs=require("fs"),f=process.argv[2],retry=process.argv[3],o=JSON.parse(fs.readFileSync(f));o.retry_of=retry;fs.writeFileSync(f,JSON.stringify(o));
NODE
[ "$ALLOC_HASH" = "$ALLOC_AFTER" ]&&ok "AC-TEL-6 report never mutates model allocation"||bad "AC-TEL-6 policy mutation"
bash "$TEL" report --worktree "$REPO" --from 2026-07-01T00:00:00Z --to 2026-08-01T00:00:00Z --minimum-samples 99 --minimum-completeness 1 > "$TMP/suppressed.json";node -e 'const r=require(process.argv[1]);process.exit(r.cohorts.length===0&&r.suppressed_cohorts.length>0?0:1)' "$TMP/suppressed.json"&&ok "AC-TEL-6 small cohorts are suppressed"||bad "AC-TEL-6 suppression"

# AC-TEL-3/4/8 malformed time, stale HEAD, secret path; concurrent identical append.
make_round 22;make_run 22 1 exited 2026-07-20T05:01:00Z 2026-07-20T05:00:00Z 0;collect 22 1 implementation "$NA" "" none >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 negative duration rejected"||bad "AC-TEL-3 time"
make_run 22 1 exited 2026-07-20T05:00:00Z 2026-07-20T05:01:00Z 0;node -e 'const fs=require("fs"),f=process.argv[1],o=require(f);o.head_sha="0000000000000000000000000000000000000000";fs.writeFileSync(f,JSON.stringify(o))' "$REPO/.review/ISSUE-22-ROUND-STATE.json";collect 22 1 implementation "$NA" "" none >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 stale HEAD rejected"||bad "AC-TEL-3 stale"
make_round 22;cp "$REPO/.review/ISSUE-22-RUN.json" "$REPO/.review/SECRET_TOKEN.json";bash "$TEL" collect --issue 22 --worktree "$REPO" --round-state .review/ISSUE-22-ROUND-STATE.json --run .review/SECRET_TOKEN.json --manifest-revision 1 --attempt 1 --round 0 --role implementation --task-class workflow --model gpt-5.6-terra --effort low --transport cmux --salt-file .agent-workflow/telemetry-salt >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-4 secret-shaped artifact path rejected"||bad "AC-TEL-4 secret path"
make_round 26;make_run 26 1 exited 2026-07-20T05:02:00Z 2026-07-20T05:03:00Z 0;make_verify 26 pass;make_closure 26 1 closed 0000000000000000000000000000000000000000;collect 26 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 mismatched closure HEAD rejected"||bad "AC-TEL-3 closure identity"
# Closure freshness is bound to canonical dependency bytes and generation/admission time.
make_round 30;make_run 30 1 exited 2026-07-20T06:00:00Z 2026-07-20T06:01:00Z 0;make_verify 30 pass;make_closure 30 1 closed;node -e 'const fs=require("fs"),f=process.argv[1],o=require(f);o.integration_sha256="f".repeat(64);fs.writeFileSync(f,JSON.stringify(o))' "$REPO/.review/ISSUE-30-CLOSURE.json";collect 30 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 arbitrary integration digest rejected"||bad "AC-TEL-3 integration digest"
make_round 31;make_run 31 1 exited 2026-07-20T07:00:00Z 2026-07-20T07:01:00Z 0;make_verify 31 pass;make_closure 31 1 closed;node -e 'const fs=require("fs"),f=process.argv[1],o=require(f);o.evaluated_at=new Date(Date.parse(o.evaluated_at)-10*60*60*1000).toISOString();fs.writeFileSync(f,JSON.stringify(o))' "$REPO/.review/ISSUE-31-CLOSURE.json";collect 31 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 ten-hour stale closure rejected"||bad "AC-TEL-3 stale closure"
make_round 32;make_run 32 1 exited 2026-02-28T05:00:00Z 2026-02-28T05:01:00Z 0;make_verify 32 pass;make_closure 32 1 closed;node -e 'const fs=require("fs"),f=process.argv[1],o=require(f);o.evaluated_at="2026-02-30T05:02:00Z";fs.writeFileSync(f,JSON.stringify(o))' "$REPO/.review/ISSUE-32-CLOSURE.json";collect 32 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 impossible RFC3339 calendar date rejected"||bad "AC-TEL-3 impossible date"
make_round 33;make_run 33 1 exited 2026-07-20T08:00:00Z 2026-07-20T08:01:00Z 0;make_verify 33 pass;make_closure 33 1 closed;mv "$REPO/.review/ISSUE-33-INTEGRATION.json" "$TMP/outside-integration.json";ln -s "$TMP/outside-integration.json" "$REPO/.review/ISSUE-33-INTEGRATION.json";collect 33 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 canonical dependency symlink escape rejected"||bad "AC-TEL-3 dependency realpath"
make_round 34;make_run 34 1 exited 2026-07-20T09:00:00Z 2026-07-20T09:01:00Z 0;make_verify 34 pass;make_closure 34 1 closed;node - "$REPO/.review/ISSUE-34-INTEGRATION.json" "$REPO/.review/ISSUE-34-CLOSURE.json" <<'NODE'
const fs=require("fs"),crypto=require("crypto"),[integrationFile,closureFile]=process.argv.slice(2),integration=JSON.parse(fs.readFileSync(integrationFile)),closure=JSON.parse(fs.readFileSync(closureFile));integration.status="blocked";integration.failure_code="blocked";fs.writeFileSync(integrationFile,JSON.stringify(integration));closure.integration_sha256=crypto.createHash("sha256").update(fs.readFileSync(integrationFile)).digest("hex");fs.writeFileSync(closureFile,JSON.stringify(closure));
NODE
collect 34 1 verification "$NA" "" verify yes >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-3 schema-valid blocked integration rejected semantically"||bad "AC-TEL-3 dependency semantics"
# Existing salt/store components may be benign in-project symlinks, but never escapes.
mkdir -p "$REPO/local-telemetry-store";printf '%s' inside-salt > "$REPO/local-salt";ln -s ../local-salt "$REPO/.agent-workflow/inside-salt";ln -s ../local-telemetry-store "$REPO/.agent-workflow/inside-store";make_round 28;make_run 28 1 exited 2026-07-20T05:04:00Z 2026-07-20T05:05:00Z 1;collect 28 1 implementation "$NA" "" none no gpt-5.6-terra .agent-workflow/inside-salt .agent-workflow/inside-store >/dev/null 2>&1;[ "$?" -eq 0 ]&&ok "AC-TEL-4 benign target-local salt/store symlinks accepted"||bad "AC-TEL-4 benign symlinks"
printf '%s' outside-salt > "$TMP/outside-salt";mkdir -p "$TMP/outside-store";ln -s "$TMP/outside-salt" "$REPO/.agent-workflow/outside-salt";ln -s "$TMP/outside-store" "$REPO/.agent-workflow/outside-store";make_round 29;make_run 29 1 exited 2026-07-20T05:06:00Z 2026-07-20T05:07:00Z 1;collect 29 1 implementation "$NA" "" none no gpt-5.6-terra .agent-workflow/outside-salt >/dev/null 2>&1;[ "$?" -ne 0 ]&&ok "AC-TEL-4 salt symlink escape rejected"||bad "AC-TEL-4 salt escape";collect 29 1 implementation "$NA" "" none no gpt-5.6-terra .agent-workflow/telemetry-salt .agent-workflow/outside-store/new-child >/dev/null 2>&1;[ "$?" -ne 0 ]&&[ ! -e "$TMP/outside-store/new-child" ]&&ok "AC-TEL-4 created store cannot escape through symlink component"||bad "AC-TEL-4 store escape"
(collect 22 1 implementation "$NA" "" none >/dev/null)& p1=$!;(collect 22 1 implementation "$NA" "" none >/dev/null)& p2=$!;wait "$p1";e1=$?;wait "$p2";e2=$?;[ "$e1" -eq 0 ]&&[ "$e2" -eq 0 ]&&ok "AC-TEL-7 concurrent identical append is safe"||bad "AC-TEL-7 concurrency"
if ! grep -R -E 'target-local-salt-not-a-secret|smoke@example|/Users/' "$REPO/.agent-workflow/telemetry/samples" >/dev/null;then ok "AC-TEL-4 sample excludes secret/user/path bodies";else bad "AC-TEL-4 privacy";fi
# AC-TEL-8 enumerates this offline regression matrix. AC-TEL-9 docs define the
# evidence threshold; AC-TEL-7 deletion remains explicit operator-only.
echo "---";[ "$FAILURES" -eq 0 ]&&{ echo "ALL CASES PASS";exit 0;};echo "$FAILURES CASE(S) FAILED";exit 1
